name: Run SSHX

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sshx:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run SSHX
      run: |
        curl -sSf https://sshx.io/get | sh -s run
